### ISSUE TITLE
What is the WASM release you are using for this?

### ISSUE THREAD

**Issue by coinchimp** [KaffinPX/Kaspool#4]
Hi,

I downloaded the last release of WASM SDK from [Kaspanet](https://github.com/kaspanet/rusty-kaspa/releases)
I moved nodejs to `./wasm/kaspa` as you have indicated in the imports
I got this issue:

```bash
## `bun run index.ts` command output
1 | (function (entry, fetcher)
    ^
SyntaxError: Export named 'PoW' not found in module '/home/coinchimp/Kaspool/wasm/kaspa/kaspa.js'.

Bun v1.1.18 (Linux x64 baseline)
```
I don't see PoW exported anywhere in WASM files.

Thanks,
Mau

**Comment by KaffinPX** [comment]
PoW is a new feature on WASM library, you need latest(development) version from aspectron repo.

**Comment by coinchimp** [comment]
`master` branch??? -> https://github.com/aspectron/rusty-kaspa/blob/master/wasm/build-node-dev
